name: test

on:
  push:
    branches:
      - main

jobs:
  Test:
    name: test
    runs-on: Ubuntu-latest
    steps:
      - name: commands
        run: |
          sudo apt update
          sudo apt install clang-format-17